#!/usr/bin/env python3

"""Check for trailing whitespaces."""

import codecs
import sys
import os
import re

_twsp = re.compile(".*\s$")

line = 0
ret = 0

file_ = os.path.abspath(sys.argv[1])
with codecs.open(file_, encoding="UTF-8") as in_:
    for i, line in enumerate(in_.readlines()):
        line = line.strip("\n\r")
        if _twsp.match(line):
            ret = 1
            print("%s:%d:%d: error: trailing whitespace" % (
                file_,
                i + 1,
                len(line) - 1
            ))
sys.exit(ret)
